version: "3.8"

networks:
  vpn:
    external: true
    name: vpn

services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro #SOCKETHERE
      - ./etc:/app/public
    ports:
      - PORT1:80
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    #labels:
      #traefik.enable: true
      #traefik.http.routers.dashy.entrypoints: web,websecure
      #traefik.http.routers.dashy.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.dashy.tls: true
      #traefik.http.routers.dashy.tls.certresolver: production
      #traefik.http.services.dashy.loadbalancer.server.port: 80
      #traefik.http.routers.dashy.middlewares:
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
