networks:
  vpn:
    external: true

services:
  portainer:
    ports:
      - '8000:8000'
      - '9000:9000'
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro #SOCKETHERE
      - ./portainer-data/:/data
    image: portainer/portainer-ce
    #labels:
      #traefik.enable: true
      #traefik.http.routers.portainer.entrypoints: web,websecure
      #traefik.http.routers.portainer.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.portainer.service: portainer
      #traefik.http.routers.portainer.tls: true
      #traefik.http.routers.portainer.tls.certresolver: production
      #traefik.http.services.portainer.loadbalancer.server.port: 9000
      #traefik.http.routers.portainer.middlewares:
    networks:
      vpn:
         ipv4_address: IPADDRESSHERE
