version: "3.8"

networks:
  vpn:
    external: true

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: "DOCKERINSTALLUSERID:DOCKERINSTALLUSERID"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - "--web.listen-address=0.0.0.0:PORT1"
    ports:
      - PORT1:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prom_data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro #SOCKETHERE
    #labels:
      #traefik.enable: true
      #traefik.http.routers.prometheus.entrypoints: web,websecure
      #traefik.http.routers.prometheus.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.prometheus.tls: true
      #traefik.http.routers.prometheus.tls.certresolver: production
      #traefik.http.services.prometheus.loadbalancer.server.port: PORT1
      #traefik.http.routers.prometheus.middlewares:
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
