version: "3.5"

networks:
  vpn:
    external: true
    name: vpn

services:
  collabora:
    image: collabora/code
    container_name: collabora
    environment:
      - TZ=TIMEZONEHERE
      - domain=cloud.DOMAINNAMEHERE
      - server_name=DOMAINSUBNAMEHERE
      - username=RANDOMIZEDPASSWORD # This will be generated, no need to edit!
      - password=RANDOMIZEDPASSWORD # This will be generated, no need to edit!
      - "SLEEPFORDEBUGGER=0"
      - "extra_params = --o:ssl.enable=false --o:ssl.termination=true"
    ports:
      - "PORT1:9980"
    cap_add:
      - MKNOD
    restart:
      unless-stopped
    #labels:
      #traefik.enable: true
      #traefik.http.routers.collabora.entrypoints: web,websecure
      #traefik.http.routers.collabora.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.collabora.tls: true
      #traefik.http.routers.collabora.tls.certresolver: production
      #traefik.http.services.collabora.loadbalancer.server.port: PORT1
      #traefik.http.routers.collabora.middlewares:
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
