networks:
  vpn:
    external: true

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
     - GF_SERVER_ROOT_URL=https://DOMAINSUBNAMEHERE/
     - GF_INSTALL_PLUGINS=grafana-clock-panel
     - GF_SERVER_HTTP_PORT=PORT1
    ports:
     - 'PORT1:3000'
    volumes:
     - ./grafana_storage:/var/lib/grafana
     - /var/run/docker.sock:/var/run/docker.sock:ro #SOCKETHERE
    #labels:
      #traefik.enable: true
      #traefik.http.routers.grafana.entrypoints: web,websecure
      #traefik.http.routers.grafana.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.grafana.tls: true
      #traefik.http.routers.grafana.tls.certresolver: production
      #traefik.http.services.grafana.loadbalancer.server.port: PORT1
      #traefik.http.routers.grafana.middlewares:
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
