networks:
  vpn:
    external: true
    name: vpn

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "PORT1:8096" # HTTP Port
    #user: UIDHERE:GIDHERE
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
      - ./media2:/media2:ro
    #labels:
      #traefik.enable: true
      #traefik.http.routers.jellyfin.entrypoints: web,websecure
      #traefik.http.routers.jellyfin.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.jellyfin.tls: true
      #traefik.http.routers.jellyfin.tls.certresolver: production
      #traefik.http.routers.jellyfin.service: jellyfin
      #traefik.http.services.jellyfin.loadbalancer.server.port: PORT1
      #traefik.http.routers.jellyfin.middlewares:
    healthcheck:
      disable: false #HEALTHCHECKHERE
    restart: 'unless-stopped'
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
