version: '3.9'

networks:
  vpn:
    external: true

services:
  sshdownload:
    image: httpd:latest
    container_name: sshdownload
    ports:
    - 'PORT1:80'
    volumes:
    - /docker/ssh/private:/usr/local/apache2/htdocs
    networks:
      vpn:
         ipv4_address: IPADDRESSHERE
