networks:
  vpn:
    external: true

services:
  ipinfo:
    container_name: ipinfo
    image: peterdavehello/ipinfo.tw:latest
    restart: unless-stopped
    ports:
      - PORT1:8080
    #labels:
      #traefik.enable: true
      #traefik.http.routers.ipinfo.entrypoints: web,websecure
      #traefik.http.routers.ipinfo.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.ipinfo.tls: true
      #traefik.http.routers.ipinfo.tls.certresolver: production
      #traefik.http.routers.ipinfo.middlewares:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro #SOCKETHERE
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
