networks:
  vpn:
    external: true

services:
  speedtest:
    image: adolfintel/speedtest
    container_name: speedtest
    environment:
      - MODE=standalone
      - TELEMETRY=false
      - ENABLE_ID_OBFUSCATION=true
      - PASSWORD=asGA5sa9ajsomtf
      - WEBPORT=80
    ports:
      - 4001:80
    #labels:
      #traefik.enable: true
      #traefik.http.routers.speedtest.entrypoints: web,websecure
      #traefik.http.routers.speedtest.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.speedtest.tls: true
      #traefik.http.routers.speedtest.tls.certresolver: production
      #traefik.http.routers.speedtest.middlewares:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro #SOCKETHERE
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
