version: "3"

networks:
  vpn:
    external: true

services:
  unbound:
    image: "mvance/unbound:latest"
    container_name: unbound
    restart: unless-stopped
    hostname: "unbound"
    volumes:
      - "./etc:/opt/unbound/etc/unbound/"
    networks:
      vpn:
        ipv4_address: 10.8.1.119

  adguard:
    depends_on: [unbound]
    container_name: adguard
    image: adguard/adguardhome
    restart: unless-stopped
    hostname: adguard
    ports:
      #- 53:53/tcp
      #- 53:53/udp
      #- 3784:784/udp
      #- 853:853/tcp
      - PORT1:3000/tcp # Setup
      - PORT2:80/tcp # Admin
      #- 3443:443/tcp
    #labels:
      #traefik.enable: true
      #traefik.http.routers.adguard-admin.entrypoints: web,websecure
      #traefik.http.routers.adguard-admin.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.adguard-admin.tls: true
      #traefik.http.routers.adguard-admin.tls.certresolver: production
      #traefik.http.services.adguard-admin.loadbalancer.server.port: PORT2
      #traefik.http.routers.adguard-admin.middlewares:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro #SOCKETHERE
      - "./work:/opt/adguardhome/work"
      - "./conf:/opt/adguardhome/conf"
      - "./tailscale:/usr/local/bin/"
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
