networks:
  vpn:
    external: true
    name: vpn

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TIMEZONEHERE
      - APP_URL=https://DOMAINSUBNAMEHERE
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS=RANDOMIZEDPASSWORD1
      - DB_DATABASE=bookstackapp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro #SOCKETHERE
      - ./data:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
    healthcheck:
      disable: false #HEALTHCHECKHERE
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=TIMEZONEHERE
      - MYSQL_ROOT_PASSWORD=RANDOMIZEDPASSWORD1
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=RANDOMIZEDPASSWORD1
    volumes:
      - ./db:/config
    restart: unless-stopped
    networks:
      vpn:
        ipv4_address: 10.8.1.130
