networks:
  vpn:
    external: true

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    volumes:
      - ./data/:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - PORT1:8080
    environment:
      - APACHE_PORT=PORT2
      - APACHE_DISABLE_REWRITE_IP=1
      - NEXTCLOUD_TRUSTED_DOMAINS=DOMAINSUBNAMEHERE 10.8.1.5 # Your domain name + proxy host IP
      - TRUSTED_PROXIES=10.8.1.5 # proxy host IP
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE