version: '3'

networks:
  vpn:
    external: true

services:
  actual_server:
    image: actualbudget/actual-server:latest
    container_name: actual
    ports:
      - 'PORT1:PORT1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./actual-data:/data
    #labels:
      #traefik.enable: true
      #traefik.http.routers.actual.entrypoints: web,websecure
      #traefik.http.routers.actual.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.actual.tls: true
      #traefik.http.routers.actual.tls.certresolver: production
      #traefik.http.routers.actual.middlewares:
      #traefik.http.services.actual.loadbalancer.server.port: PORT1
    restart: unless-stopped
    networks:
      vpn:
         ipv4_address: IPADDRESSHERE
