networks:
  vpn:
    external: true

services:
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    ports:
     - PORT1:8080
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro #SOCKETHERE
      - ./searxng-data/:/etc/searxng:rw
    #environment:
      #- SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    #labels:
      #traefik.enable: true
      #traefik.http.routers.searxng.entrypoints: web,websecure
      #traefik.http.routers.searxng.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.searxng.tls: true
      #traefik.http.routers.searxng.tls.certresolver: production
      #traefik.http.routers.searxng.middlewares:
    healthcheck:
      disable: false #HEALTHCHECKHERE
    networks:
      vpn:
         ipv4_address: IPADDRESSHERE
