#!/bin/bash

docker_scripts=(
    "docker/app/down.sh"
    "docker/app/functions.sh"
    "docker/app/start.sh"
    "docker/app/stop.sh"
    "docker/app/uninstall.sh"
    "docker/app/up.sh"
    "docker/app/update.sh"
    "docker/install/functions.sh"
    "docker/install/rooted.sh"
    "docker/install/rootless.sh"
    "docker/checks.sh"
    "docker/command.sh"
    "docker/compose.sh"
    "docker/configs.sh"
    "docker/misc.sh"
    "docker/scan.sh"
    "docker/service.sh"
    "docker/switcher.sh"
)
