#!/bin/bash

menu_scripts=(
    "menu/message/complete.sh"
    "menu/message/continue.sh"
    "menu/message/final.sh"
    "menu/message/instructions.sh"
    "menu/message/login.sh"
    "menu/message/markers.sh"
    "menu/message/public.sh"
    "menu/tools/manage_crontab.sh"
    "menu/tools/manage_dashy.sh"
    "menu/tools/manage_docker.sh"
    "menu/tools/manage_invidious.sh"
    "menu/tools/manage_main.sh"
    "menu/tools/manage_mattermost.sh"
    "menu/tools/manage_ssh.sh"
    "menu/tools/manage_tools.sh"
    "menu/tools/manage_wireguard.sh"
    "menu/mainmenu.sh"
    "menu/scan_category.sh"
    "menu/reset_to_menu.sh"
)
