#!/bin/bash

menu_scripts=(
    "menu/message/complete.sh"
    "menu/message/continue.sh"
    "menu/message/final.sh"
    "menu/message/instructions.sh"
    "menu/message/login.sh"
    "menu/message/markers.sh"
    "menu/message/public.sh"
    "menu/tools/crontab.sh"
    "menu/tools/dashy.sh"
    "menu/tools/docker.sh"
    "menu/tools/invidious.sh"
    "menu/tools/main.sh"
    "menu/tools/mattermost.sh"
    "menu/tools/ssh.sh"
    "menu/tools/tools.sh"
    "menu/tools/wireguard.sh"
    "menu/functions.sh"
    "menu/mainmenu.sh"
    "menu/reset.sh"
)
