#!/bin/bash

migrate_scripts=(
    "migrate/file/check.sh"
    "migrate/file/restore/files_to_migrate.sh"
    "migrate/file/restore/file_from_migrate.sh"
    "migrate/file/restore/file_to_migrate.sh"
    "migrate/file/update.sh"
    "migrate/list/full.sh"
    "migrate/list/single.sh"
    "migrate/txt/build.sh"
    "migrate/txt/generate_all.sh"
    "migrate/txt/generate_single.sh"
    "migrate/txt/sanitize.sh"
    "migrate/txt/scan.sh"
    "migrate/txt/update_install.sh"
    "migrate/txt/update_ip.sh"
    "migrate/enable_config.sh"
    "migrate/get_app_name.sh"
)
