#https://github.com/harveyconnor/traefikv2-docker-gitlab
networks:
  vpn:
    external: true
services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: always
    ports:
      - "PORT2:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url DOMAINSUBNAMEHERE
        nginx['listen_https'] = false
        nginx['listen_port'] = PORT1
    #labels:
      #traefik.enable: true
      #traefik.http.routers.gitlab.rule: Host(DOMAINSUBNAMEHERE)
      #traefik.http.routers.gitlab.entrypoints: web,websecure
      #traefik.http.routers.gitlab.tls.certresolver: production
      #traefik.http.services.gitlab.loadbalancer.server.port: PORT1
      #traefik.docker.network: DOCKERNETWORK
      #traefik.tcp.routers.gitlab-ssh.rule: HostSNI(DOMAINSUBNAMEHERE)
      #traefik.tcp.routers.gitlab-ssh.entrypoints: ssh
      #traefik.tcp.routers.gitlab-ssh.service: gitlab-ssh-svc
      #traefik.tcp.services.gitlab-ssh-svc.loadbalancer.server.port: PORT2
      #traefik.http.routers.gitlab.middlewares:
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
    shm_size: '256m'

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro #SOCKETHERE
      - ./runner/config/:/etc/gitlab-runner:Z
    networks:
      vpn:
        ipv4_address: 10.8.1.115
    labels:
      - traefik.enable=false
