networks:
  vpn:
    external: true

services:
  trilium:
    image: zadam/trilium
    container_name: trilium
    restart: always
    environment:
      - TRILIUM_DATA_DIR=/home/node/trilium-data
    ports:
      - "PORT1:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro #SOCKETHERE
      - ./trilium-data/:/home/node/trilium-data
    #labels:
      #traefik.enable: true
      #traefik.http.routers.trilium.entrypoints: web,websecure
      #traefik.http.routers.trilium.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.trilium.tls: true
      #traefik.http.routers.trilium.tls.certresolver: production
      #traefik.http.services.trilium.loadbalancer.server.port: PORT1
      #traefik.http.routers.trilium.middlewares:
    networks:
      vpn:
         ipv4_address: IPADDRESSHERE
