networks:
  vpn:
    external: true
    name: vpn

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - PORT1:80
      - PORT2:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro #SOCKETHERE
      - ./etc:/etc/traefik
    #labels:
      #traefik.docker.network: DOCKERNETWORKHERE
      #traefik.enable: "true"
      #traefik.http.routers.traefik.entrypoints: web,websecure
      #traefik.http.routers.traefik.rule: Host(`DOMAINSUBNAMEHERE`)
      #traefik.http.routers.traefik.service: api@internal
      #traefik.http.routers.traefik.tls: true
      #traefik.http.routers.traefik.tls.certresolver: production
      #traefik.http.routers.traefik.tls.options: modern@file
      #traefik.http.routers.traefik.middlewares:
    healthcheck:
      disable: false #HEALTHCHECKHERE
    restart: unless-stopped
    networks:
      vpn:
        ipv4_address: IPADDRESSHERE
